apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: demo

images:
- name: demo
  newName: netodevel/gitops
  newTag: 3004a87940924aae09cc9b3ba3c3362ce250fd0b
