name: bump version
on:
  push:
    branches: [development]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: 'adopt'
          cache: maven

      - name: get last branch name
        run:  export BRANCH_NAME=$(git log --oneline -n 2 | grep -oP "([a-z\d]+[-\/_.]?)*[a-z\d]$" | grep netodevel/ | awk -F "/" '{print $2 "/" $3}')

      - name: get last branch name
        run:  echo env.BRANCH_NAME

      - name: get last branch name
        run:  echo $env.BRANCH_NAME

      - name: Bump minor version
        if: env.BRANCH_NAME=='feature/test-hacker'
        run: mvn --batch-mode build-helper:parse-version versions:set -DnewVersion='${parsedVersion.majorVersion}.${parsedVersion.nextMinorVersion}.0-SNAPSHOT' versions:commit

      - name: commit
        run: | 
          git config --local user.email "josevieira.dev@gmail.com"
          git config --local user.name "netodevel"
          git add pom.xml
          git commit -m "bump(dev): change minor version"

      - name: push
        uses: ad-m/github-push-action@master
        with:
          branch: development
