name: release
on:
  push:
    branches: [development]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: 'adopt'
          cache: maven
      - name: Bump minor version
        run: mvn --batch-mode build-helper:parse-version versions:set -DnewVersion='${parsedVersion.majorVersion}.${parsedVersion.nextMinorVersion}.0-SNAPSHOT' versions:commit
      - name: commit
        run: | 
          git config --local user.email "josevieira.dev@gmail.com"
          git config --local user.name "netodevel"
          git add pom.xml
          git commit -m "ci: change image tag"